---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring
  profiles: primary
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurika-secondary:8011/eureka/,http://eurika-tertiary:8012/eureka/

---
spring
  profiles: secondary
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurika-primary:8010/eureka/,http://eurika-tertiary:8012/eureka/


---
spring
  profiles: tertiary
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurika-primary:8010/eureka/,http://eurika-secondary:8011/eureka/
