---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8010  
eureka:
  instance:
    hostname: eurekahost 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
